services:
  postgresdb:
    image: postgres
    restart: unless-stopped

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/templates:/etc/alertmanager/templates
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - /prometheus/alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--log.level=debug'
      - '--web.external-url=http://localhost:9093'
    depends_on:
      - prometheus

  elasticsearch:
    image: 'elasticsearch:7.17.28'
    volumes:
      - ./conf/elasticsearch/conf.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data:z
    platform: linux/amd64
    container_name: 'elasticsearch'
    restart: 'unless-stopped'
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - 'bootstrap.memory_lock=true'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: 'curl -f http://localhost:9200 || exit 1'

  logstash:
    image: 'logstash:7.17.28'
    container_name: 'logstash'
    restart: 'unless-stopped'
    ports:
       - "5044:5044"
       - "5010:5000"
       - "9600:9600"
    volumes:
      - './logstash/pipeline:/usr/share/logstash/pipeline/'
      - ./conf/logstash/conf.yml:/usr/share/logstash/config/logstash.yml:ro
    depends_on:
      - 'elasticsearch'
    healthcheck:
      test: 'curl -f http://localhost:9600 || exit 1'

  kibana:
    image: 'kibana:7.17.28'
    container_name: 'kibana'
    restart: 'unless-stopped'
    ports:
      - '5601:5601'
    environment:
      - 'ELASTICSEARCH_HOSTS=http://elasticsearch:9200'
    volumes:
      - ./conf/kibana/conf.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - 'elasticsearch'
    healthcheck:
      test: 'curl -f http://localhost:5601 || exit 1'

  filebeat:
    build: 'filebeat'
    container_name: 'filebeat'
    restart: 'unless-stopped'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/lib/docker/containers:/usr/share/dockerlogs/data:ro'
    depends_on:
      - 'elasticsearch'
      - 'logstash'

  prometheus:
    image: 'prom/prometheus:v3.4.0'
    container_name: 'prometheus'
    restart: 'unless-stopped'
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - './prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml'
    ports:
      - '9090:9090'
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9090" ]

  grafana:
    image: 'grafana/grafana:12.0.1'
    container_name: 'grafana'
    restart: 'unless-stopped'
    ports:
      - '3000:3000'
    environment:
      - 'GF_USERS_ALLOW_SIGN_UP=false'
    volumes:
      - './grafana/provisioning:/etc/grafana/provisioning'
    depends_on:
      - 'prometheus'
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "3000" ]

  app:
    depends_on:
      postgresdb:
        condition: service_healthy
    image: batch-processing
    restart: unless-stopped
    ports:
    - "8080:8080"
    build:
      context: .
      dockerfile: ./Dockerfile

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./var/log/nginx:/var/log/nginx

    ports:
      - 80:80